name: Bug report
description: Report a bug or detection issue
body:
  - type: textarea
    id: cli-output
    attributes:
      label: "`extra-platforms` output"
      description: |
        Run that CLI and paste the full output to share the state of the current context:
        ```shell-session
        $ uvx extra-platforms
        ```

        The development version may already include a fix or improved detection for your issue.
        To test it, you can install it directly from the repository and share the output as well:
        ```shell-session
        $ uvx --from 'extra-platforms @ git+https://github.com/kdeldycke/extra-platforms.git' extra-platforms
        ```
      render: text
    validations:
      required: true
