flowchart TD
    classDef missing stroke-dasharray: 5
    boltons["boltons\n25.0.0"]
    distro["distro\n1.9.0"]
    extra-platforms["extra-platforms\n3.2.3"]
    extra-platforms -- "~=1.9.0" --> distro
    extra-platforms -- "~=25.0.0" --> boltons

