---
name: ✂️ Cancel runs
"on":
  workflow_dispatch:
  pull_request:
    types:
      - closed

jobs:

  cancel-runs:
    uses: kdeldycke/repomatic/.github/workflows/cancel-runs.yaml@f600fefb41f28a11f550f43d8145b96438e46b84 # v6.14.0
