---
name: 🚀 Build & release
"on":
  workflow_dispatch:
  push:
    branches:
      - main

jobs:

  release:
    uses: kdeldycke/repomatic/.github/workflows/release.yaml@f185b237deb05defc94f8dff02a82a2d9bd579d8 # v6.20.0
    secrets:
      REPOMATIC_PAT: ${{ secrets.REPOMATIC_PAT }}
      VIRUSTOTAL_API_KEY: ${{ secrets.VIRUSTOTAL_API_KEY }}

  publish-pypi:
    name: 🐍 Publish to PyPI (${{ matrix.short_sha }})
    needs: release
    if: needs.release.outputs.release_commits_matrix
    strategy:
      matrix: ${{ fromJSON(needs.release.outputs.release_commits_matrix) }}
    runs-on: ubuntu-latest
    permissions:
      id-token: write
    steps:
      - uses: kdeldycke/repomatic/.github/actions/publish-pypi@f185b237deb05defc94f8dff02a82a2d9bd579d8 # v6.20.0
        with:
          artifact-name: ${{ github.event.repository.name }}-${{ matrix.short_sha }}
